OSOE-572: Add "Generate Reset Password Token" workflow activity
Lombiq/Helpful-Extensions pull request #113
Opened 2023-02-15 17:12 UTC by barthamark

OSOE-572

2023-02-23 17:21 UTC, dministro requested changes

2023-02-23 17:21 UTC, dministro commented on Readme.md
> +- GenerateResetPasswordTask: Generates a reset password token for the user found in the Workflow context or the current user. The token is set to the Workflow properties to the `ResetPasswordToken` k
Why we don't add `OrchardCore.Users.ResetPassword` as feature dependency?

2023-02-23 17:21 UTC, dministro commented on Lombiq.HelpfulExtensions/FeatureIds.cs
> +    public const string Workflows = FeatureIdPrefix + nameof(Workflows);
I would suggest a new feature id since we have a feature that depends on an OC feature `OrchardCore.Users.ResetPassword` but possibly not all `Workflow` features will depend on it. 
See my comment for `Readme.md`.
```suggestion
    public const string Workflows = FeatureIdPrefix + nameof(Workflows);
    public const string ResetPasswordActivity = Workflows + "." + nameof(ResetPasswordActivity);
```

2023-02-23 17:21 UTC, dministro commented on Lombiq.HelpfulExtensions/Manifest.cs
> +)]
As a continuation of my suggestion for `FeatureIds.cs`.

```suggestion
[assembly: Feature(
    Id = Workflows,
    Name = "Lombiq Helpful Extensions - Workflows",
    Category = "Workflows",
    Description = "Adds useful workflow activities (e.g., generate reset password token).",
    Dependencies = new[]
    {
        "OrchardCore.Workflows",
    }
)]

[assembly: Feature(
    Id = ResetPasswordActivity,
    Name = "Lombiq Helpful Extensions - Reset password workflow activity",
    Category = "Workflows",
    Description = "Adds generate reset password token activity.",
    Dependencies = new[]
    {
        Workflows,
        "OrchardCore.Users.ResetPassword",
    }
)]
```

2023-02-23 17:21 UTC, dministro commented on Lombiq.HelpfulExtensions/Extensions/Workflows/Activities/GenerateResetPasswordTokenTask.cs
> +        if (user == null) return Outcomes("Done", "Done");
Why we don't have an `Error` outcome for this case?
Why double `Done` here and below?

2023-02-23 17:21 UTC, dministro commented on Lombiq.HelpfulExtensions/Extensions/Workflows/Activities/GenerateResetPasswordTokenTask.cs
> +        }
I would expect some configuration regarding the source of the `User` object instead of these complex conditions with hard-coded values.

2023-02-23 17:21 UTC, dministro commented on Lombiq.HelpfulExtensions/Extensions/Workflows/Activities/GenerateResetPasswordTokenTask.cs
> +        workflowContext.Properties["ResetPasswordUrl"] = resetPasswordUrl;
I would expect some configuration regarding the results instead of using hard-coded keys. Here and above. (`ResetPasswordUrl`, `ResetPasswordToken`)

2023-02-26 06:41 UTC, barthamark commented on Lombiq.HelpfulExtensions/FeatureIds.cs
> +    public const string Workflows = FeatureIdPrefix + nameof(Workflows);
Good point for this and above. I've named it ResetPassword though.

2023-02-26 06:47 UTC, barthamark commented on Lombiq.HelpfulExtensions/Manifest.cs
> +)]
There are no other workflow-related features so I don't see the point of creating a Workflows features now. What do you think?

2023-02-26 12:38 UTC, dministro commented on Lombiq.HelpfulExtensions/Manifest.cs
> +)]
I can agree, we can drop the `Workflows` feature.

2023-02-28 16:26 UTC, dministro approved these changes

2023-02-28 16:26 UTC, dministro commented on Lombiq.HelpfulExtensions/Extensions/Workflows/Activities/GenerateResetPasswordTokenTask.cs
> +        var user = !string.IsNullOrEmpty(User.Expression)
This check is not necessary. See: https://github.com/OrchardCMS/OrchardCore/blob/68c5f85470ca1d9bd2663c011aa4f67138de2ab5/src/OrchardCore.Modules/OrchardCore.Workflows/Scripting/JavaScriptWorkflowScriptEvaluator.cs#L32

2023-02-28 17:45 UTC, dministro approved these changes

2023-02-28 17:45 UTC, merged