OSOE-706: Add Orchard 1 User migration feature
Lombiq/Helpful-Extensions pull request #152
Opened 2023-10-20 17:19 UTC by MZole

2023-10-23 22:05 UTC, DemeSzabolcs requested changes

2023-10-23 22:05 UTC, DemeSzabolcs commented on Lombiq.HelpfulExtensions/Extensions/OrchardRecipeMigration/Services/UserOrchardContentConverter.cs
> +                IsEnabled = true,
Can't we get these values from the O1 users?

2023-10-23 22:05 UTC, DemeSzabolcs commented on Readme.md
> +Migrating users from Orchard 1 is also possible with this feature: Import the same way as other Orchard 1 contents, and users will generate automatically, meaning you don't have to do anything else.
```suggestion
Migrating users from Orchard 1 is also possible with this feature: Import the same way as other Orchard 1 contents, and users will be generated automatically, meaning you don't have to do anything else.
```

2023-10-23 22:05 UTC, DemeSzabolcs commented on Lombiq.HelpfulExtensions/Extensions/OrchardRecipeMigration/Services/OrchardExportToRecipeConverter.cs
> +                if (await CreateContentItemAsync(content) is not { } contentItem) continue;
I would break this to 3 part at the same level. Maybe with `switch`

2023-10-24 14:55 UTC, MZole commented on Lombiq.HelpfulExtensions/Extensions/OrchardRecipeMigration/Services/UserOrchardContentConverter.cs
> +                IsEnabled = true,
We can set `EmailConfirmed` from the O1 recipe, you are correct, but `IsEnabled` doesn't have a corresponding property in O1.

2023-10-26 12:56 UTC, DemeSzabolcs approved these changes

2023-10-26 12:58 UTC, merged