COLI-370: Analyzers: fixing the remainder of the warnings
Lombiq/Helpful-Extensions pull request #30
Opened 2021-06-10 21:53 UTC by 0liver

COLI-370

2021-07-04 10:01 UTC, BenedekFarkas requested changes

2021-07-04 10:01 UTC, BenedekFarkas commented on Extensions/InvariantExtensions.cs
> +            return value.ToString(CultureInfo.InvariantCulture);
Expression body for both functions?

2021-07-04 10:01 UTC, BenedekFarkas commented on Extensions/InvariantExtensions.cs
> +    public static class InvariantExtensions
Super nitpicky, because you don't need to know the name of this class to use the functions, but is there maybe a more descriptive name? E.g. InvariantCultureTypeConversionExtensions?

2021-07-05 07:40 UTC, 0liver commented on Extensions/InvariantExtensions.cs
> +    public static class InvariantExtensions
I'm always open for good names! They're one of the most important things we can use in our code.

I like your suggestion. I'll rename the class.

2021-07-05 07:41 UTC, 0liver commented on Extensions/InvariantExtensions.cs
> +            return value.ToString(CultureInfo.InvariantCulture);
Of course! The submodules are not yet covered by the analyzers, but we'll get there, eventually 😄

2021-07-05 13:39 UTC, BenedekFarkas commented on Extensions/InvariantExtensions.cs
> +            return value.ToString(CultureInfo.InvariantCulture);
Ah, of course!

2021-07-05 13:39 UTC, BenedekFarkas approved these changes

2021-07-05 13:57 UTC, merged