Github Actions
Lombiq/Helpful-Extensions pull request #49
Opened 2022-01-09 11:37 UTC by deanmarcussen

Fixes https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/23

Merge 3rd.

This depends on the `NuGet.config` to get HL from Cloudmsith.

(the version specified is currently available there, as I pushed it from my fork)

2022-01-09 12:02 UTC, deanmarcussen commented on Lombiq.HelpfulExtensions.csproj
> +    <PackageReference Include="Lombiq.HelpfulLibraries.Targets" Version="0.0.3" />
this will need updating after merging and building HL

2022-01-10 01:31 UTC, Piedone requested changes

2022-01-10 01:31 UTC, Piedone commented on NuGet.config
> +<?xml version="1.0" encoding="utf-8"?>
Do we still need this file?

2022-01-10 01:31 UTC, Piedone commented on Readme.md
> +confidence.
Note to self: Remove after update to NuGet.

2022-01-10 10:10 UTC, deanmarcussen commented on NuGet.config
> +<?xml version="1.0" encoding="utf-8"?>
as per your comment below:
> Note to self: Remove after update to NuGet.

2022-01-10 23:10 UTC, Piedone approved these changes

2022-01-18 21:05 UTC, merged