SNOW-52: Adding Markdown widget type
Lombiq/Helpful-Extensions pull request #62
Opened 2022-03-30 15:34 UTC by VTamas1

SNOW-52

2022-03-31 11:56 UTC, Luko6 reviewed
You have to create an OSOCE PR if you change the open source submodules.

2022-03-31 12:01 UTC, wAsnk commented
> You have to create an OSOCE PR if you change the open source submodules.

And what changes should the PR contain?

2022-03-31 12:32 UTC, DAud-IcI commented
> And what changes should the PR contain?

Create a new branch from OSOCE's `dev` called `issue/SNOW-52` and update each submodule that exists in both and you have updated here to their respective `issue/SNOW-52` branches. So HL and HE for this issue. This is for very basic regression testing on OSOCE, and to make sure all the submodules in that repo are up-to-date the same way you update the submodules here.

By the way, you don't have PRs for your HelpfulExtensions and BaseTheme branches.

2022-03-31 12:35 UTC, wAsnk commented
> > And what changes should the PR contain?
> 
> Create a new branch from OSOCE's `dev` called `issue/SNOW-52` and update each submodule that exists in both and you have updated here to their respective `issue/SNOW-52` branches. So HL and HE for this issue. This is for very basic regression testing on OSOCE, and to make sure all the submodules in that repo are up-to-date the same way you update the submodules here.
> 
> By the way, you don't have PRs for your HelpfulExtensions and BaseTheme branches.

Thanks, tho this is the HelpfulExtensions PR. The BaseTheme shouldn't be changed, @VTamas1 should remove that.
edit: You might think about HelpfulLibraries. But that should be removed aswell, there are no changes, just a simple dev => issue/SNOW-52 merge.

@VTamas1 Please checkout to the correct branch in BaseTheme and HelpfulLibraries submodule, then push in your branch in the main repo.

2022-03-31 12:37 UTC, Luko6 requested changes

2022-03-31 12:37 UTC, Luko6 commented on Extensions/Widgets/Migrations.cs.orig
> +using OrchardCore.ContentManagement.Metadata;
delete .orig file

2022-03-31 12:37 UTC, Luko6 commented on Extensions/Widgets/WidgetTypes.cs.orig
> +namespace Lombiq.HelpfulExtensions.Extensions.Widgets
delete .orig file

2022-03-31 12:37 UTC, Luko6 commented on Extensions/Widgets/Migrations.cs
> +        return 3;
Revert this change

2022-03-31 12:37 UTC, Luko6 commented on Extensions/Widgets/Migrations.cs
> +        return 4;
Revert this change

2022-03-31 12:47 UTC, sarahelsaig commented on Extensions/Widgets/Migrations.cs.orig
> +using OrchardCore.ContentManagement.Metadata;
Also add `*.orig` to the _.gitignore_ file to prevent this from the future.

2022-04-06 12:45 UTC, Luko6 approved these changes

2022-04-07 14:09 UTC, merged