OSOE-49: Enforce Windows newlines for C# files to avoid false positives with IDE0055 warning.
Lombiq/Helpful-Extensions pull request #68
Opened 2022-05-12 18:39 UTC by DAud-IcI

OSOE-49

2022-05-13 20:18 UTC, Piedone approved these changes

2022-05-23 07:35 UTC, 0liver requested changes

2022-05-23 07:35 UTC, 0liver commented on .gitattributes
> +# See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/106
```suggestion
# See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/106.
```

2022-05-23 15:51 UTC, 0liver approved these changes

2022-05-26 11:33 UTC, merged